# Generated by Django 5.0.4 on 2024-05-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathernames', models.CharField(max_length=100)),
                ('mothernames', models.CharField(max_length=100)),
                ('mariage_status', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('cell', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorname', models.CharField(max_length=100)),
                ('executive_officer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('identity', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.family')),
            ],
            options={
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellname', models.CharField(max_length=100)),
                ('executive_officer', models.CharField(max_length=300)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(max_length=100)),
                ('reason_of_capture', models.CharField(max_length=1000)),
                ('district_of_capture', models.CharField(max_length=50)),
                ('village_of_capture', models.CharField(max_length=50)),
                ('date_of_capture', models.DateTimeField()),
                ('orientation', models.CharField(max_length=100)),
                ('case_desc', models.CharField(max_length=5000)),
                ('cell_of_capture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cell')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.children')),
                ('sector_of_capture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('identity', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('responsability', models.CharField(max_length=100)),
                ('privilege', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField()),
                ('office_cell', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cell')),
                ('office_sector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('poster', models.ImageField(upload_to='images/')),
                ('video', models.FileField(upload_to='videos/')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('poster', models.ImageField(upload_to='images/')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
            },
        ),
    ]
