# Generated by Django 5.0.4 on 2024-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(),
        ),
    ]
