# Generated by Django 5.0.4 on 2024-05-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_opportunity_priority_testimonial_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='status',
            field=models.CharField(choices=[('In school', 'In school'), ('In transit center', 'In transit center'), ('In rehabilitation center', 'In rehabilitation center'), ('Re-integrated in family', 'Re-integrated in family'), ('In street', 'In street')], default='In street', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'verbose_name_plural': 'UserActivities',
            },
        ),
    ]
