# Generated by Django 5.0.4 on 2024-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_children_status_alter_opportunity_posted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='poster',
            field=models.ImageField(upload_to='posts/images/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='poster',
            field=models.ImageField(upload_to='posts/images/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=models.FileField(upload_to='posts/videos/'),
        ),
    ]
