# Generated by Django 5.0.4 on 2024-05-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_opportunity_poster_alter_testimonial_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
