# Generated by Django 5.0.4 on 2024-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_children_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='behavior',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
