# Generated by Django 5.0.4 on 2024-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
