# Generated by Django 5.0.4 on 2024-05-05 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.cell'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.sector'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privilege',
            field=models.CharField(choices=[('cellular', 'Cellular'), ('supperuser', 'Superuser'), ('sectorial', 'Sectorial')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
