# Generated by Django 5.0.4 on 2024-05-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_age_alter_user_office_cell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privilege',
            field=models.CharField(choices=[('cellular', 'Cellular'), ('sectorial', 'Sectorial')], max_length=100),
        ),
    ]
