# Generated by Django 5.0.4 on 2024-05-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_privilege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
