# Generated by Django 5.0.4 on 2024-05-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0018_remove_user_firstname_remove_user_lastname'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ScmsUser',
        ),
    ]
