# Generated by Django 5.0.4 on 2024-05-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
