# Generated by Django 5.0.4 on 2024-05-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_user_firstname_remove_user_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='office_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.cell'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.sector'),
        ),
    ]
