# Generated by Django 5.0.4 on 2024-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_office_cell_alter_user_office_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
    ]
