# Generated by Django 5.0.4 on 2024-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_opportunity_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='poster',
            field=models.ImageField(default=1, upload_to='posts/images/'),
            preserve_default=False,
        ),
    ]
