# Generated by Django 5.0.4 on 2024-05-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_opportunity_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
