# Generated by Django 5.0.4 on 2024-05-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_family_cell_alter_family_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.cell'),
        ),
        migrations.AlterField(
            model_name='family',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.sector'),
        ),
    ]
