# Generated by Django 5.0.4 on 2024-05-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_family_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='speaker',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
