# Generated by Django 5.0.4 on 2024-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_testimonial_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='status',
            field=models.CharField(choices=[('In school', 'In school'), ('In transit centre', 'In transit centre'), ('In rehabilitation center', 'In rehabilitation center'), ('Re-integrated in family', 'Re-integrated in family'), ('In street', 'In street')], default='In street', max_length=100),
        ),
    ]
