# Generated by Django 5.0.4 on 2024-05-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_children_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.family'),
        ),
    ]
