# Generated by Django 5.0.4 on 2024-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_children_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='cell',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='sector',
            field=models.CharField(max_length=50),
        ),
    ]
