# Generated by Django 5.0.4 on 2024-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_family_cell_alter_family_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='behavior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
