# Generated by Django 5.0.4 on 2024-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_children_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
