# Generated by Django 5.0.4 on 2024-05-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_children_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='behavior_desc',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
