# Generated by Django 5.0.4 on 2024-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_children_behavior_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='about_family',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Improving', 'Improving'), ('Cleared', 'Cleared'), ('Dangerous', 'Dangerous')], default='Critical', max_length=50),
        ),
    ]
