# Generated by Django 5.0.4 on 2024-05-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='residential_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
