# Generated by Django 5.0.4 on 2024-05-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='user_uuid',
        ),
    ]
