# Generated by Django 5.0.4 on 2024-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rename_user_id_user_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.CharField(default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/'),
        ),
    ]
