# Generated by Django 5.0.4 on 2024-05-31 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_opportunity_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sector'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sector'),
        ),
    ]
