# Generated by Django 5.0.4 on 2024-05-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_opportunity_sector_testimonial_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
    ]
