# Generated by Django 5.0.4 on 2024-05-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_testimonial_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/'),
        ),
    ]
