# Generated by Django 5.0.4 on 2024-06-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_opportunity_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='slag',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='slag',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
