# Generated by Django 5.0.4 on 2024-06-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_opportunity_slag_alter_testimonial_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='slag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='slag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
